spring:
  application:
    name: mybatis-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=persistence-demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver