spring:
  application:
    name: jpa-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=persistence-demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
    drop-first: true
  jpa:
    properties:
      hibernate:
        jdbc.batch_size: ${HIBERNATE_JDBC_BATCH_SIZE:30}
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect